server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"

    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.1"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH

plugins:
  youtube:
    enabled: true

    allowSearch: true
    allowDirectVideoIds: true

    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED

    oauth:
      enabled: false

  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"

    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: false

    spotify:
      clientId: "YOUR_CLIENT_ID"
      clientSecret: "YOUR_CLIENT_SECRET"
      countryCode: "US"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
