server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  youtube:
    enabled: true

    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - ANDROID

    oauth:
      enabled: false
